exclude_patterns:
 - docs/*
 - tests/*
 - src/sys/external/*
 - phpunit.php
 - vendor/*
 - composer.json
rules:
 php.use_global_variable_or_function:
  enabled: false
 git.user_specific_ignored_file:
  enabled: false
