language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
env:
  - DB=mysql

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq memcached
  - sudo /etc/init.d/memcached start
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

before_script: phpenv config-add phpunit.cnf.ini

script: phpunit

notifications:
  on_success: never
  on_failure: always