language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 7.0
  - nightly
env:
  - DB=mysql

services:
  - redis-server
  - memcached

before_install:
  - mkdir -p /home/travis/.phpenv/versions/hhvm/etc

before_script:
  - phpenv config-add phpunit.cnf.ini
  - mysql -e 'create database phpunit;'

script: phpunit --stderr

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true
  allow_failures:
   - php: 7.0
   - php: nightly
