language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
env:
  - DB=mysql

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

services:
  - memcached

before_script:
  - phpenv config-add phpunit.cnf.ini
  - mysql -e 'create database phpunit;'

script: phpunit

notifications:
  on_success: never
  on_failure: always