language: php

php:
  - 5.6
  - 5.5
  - 5.4
env:
  - DB=mysql

services:
  - redis-server

before_install:
  - sudo apt-get install memcached -y -qq
  - sudo /etc/init.d/memcached start
#  - composer self-update
#  - composer install --prefer-source --no-interaction --dev

before_script:
  - phpenv config-add phpunit.cnf.ini
  - mysql -e 'create database phpunit;'

script: phpunit

notifications:
  on_success: change
  on_failure: always
